version: '3'

services:
  postgres-db:
    image: postgres:latest
    container_name: app_postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - appnetwork

volumes:
  database_postgres:                  

networks:
  appnetwork:
    driver: bridge